### ISSUE TITLE
Request for new features

### ISSUE THREAD

**Issue by kuntzer** [vbonvin/POUET#28]
A list of possible things to add:

- [ ] select as function of angle to wind
- [x] select as function of magnitude of the star
- [x] Add PanStarrs survey to Skyview?

**Comment by vbonvin** [comment]
>  select as function of magnitude of the star 

is now Issue #54

**Comment by kuntzer** [comment]
> Add PanStarrs survey to Skyview?

is now issue #58

**Comment by kuntzer** [comment]
@vbonvin I was trying to understand how I could add a form for the the angle to wind in the scalable design, but couldn't. Mission on you: teach me that :)

**Comment by vbonvin** [comment]
Ok, will wait to have you seated next to me in the train to show you that :D
