### ISSUE TITLE
Documentation showing wrong version number

### ISSUE THREAD

**Issue by kuntzer** [vbonvin/POUET#63]
This is minor: when going to [POUET's online docs](http://pouet.readthedocs.io/en/latest/), the title bar reads ```[localisation] -- POUET 0.2 documentation```. 

Is it by design that the ```0.2``` is showing? I'd propose to remove it and only keep "POUET documentation" to simplify the maintaining process.

**Comment by vbonvin** [comment]
Don't see it. Can you sent a screenshot ?

**Comment by vbonvin** [comment]
Cannot remove it entirely - it comes with the sphinx template that generate all the pages. However, we simply need to keep the `version` and `release` variables in `docs/conf.py` up to date.
